export const QUESTIONS = [
    {
        id: 1,
        type: "singleAnswer",
        question: "Are you calm and do you have a hard for someone to get over your nerves?",
        answers: ["Yes", "No"],
        pointAnswer: 1,
    },
    {
        id: 2,
        type: "singleAnswer",
        question: "Do you rarely feel tired?",
        answers: ["Yes", "No"],
        pointAnswer: 1,
    },
    {
        id: 3,
        type: "singleAnswer",
        question: "Do you often have nightmares?",
        answers: ["Yes", "No"],
        pointAnswer: 0,
    },
    {
        id: 4,
        type: "singleAnswer",
        question: "Is it hard for you to keep focus on a specific job or task?",
        answers: ["Yes", "No"],
        pointAnswer: 0,
    },
    {
        id: 5,
        type: "singleAnswer",
        question: "Are you easily embarrassed?",
        answers: ["Yes", "No"],
        pointAnswer: 0,
    },
    {
        id: 6,
        type: "singleAnswer",
        question: "Do you feel often anxiety for someone?",
        answers: ["Yes", "No"],
        pointAnswer: 0,
    },
    {
        id: 7,
        type: "singleAnswer",
        question: "Do you rarely have heartbeats and suffocation?",
        answers: ["Yes", "No"],
        pointAnswer: 1,
    },
    {
        id: 8,
        type: "singleAnswer",
        question: "Is waiting for something makes you nervous?",
        answers: ["Yes", "No"],
        pointAnswer: 0,
    },
    {
        id: 9,
        type: "singleAnswer",
        question: "Dou you often fell hungry, even after a meal?",
        answers: ["Yes", "No"],
        pointAnswer: 0,
    },
    {
        id: 10,
        type: "singleAnswer",
        question: "Can you tell that you are more sensitive than the people around you?",
        answers: ["Yes", "No"],
        pointAnswer: 0,
    },
    {
        id: 11,
        type: "singleAnswer",
        question: "Do you have enough self-confidence?",
        answers: ["Yes", "No"],
        pointAnswer: 1,
    },

    {
        id: 12,
        type: "singleAnswer",
        question: "Does your work place involve a lot of tension?",
        answers: ["Yes", "No"],
        pointAnswer: 0,
    },
    {
        id: 13,
        type: "singleAnswer",
        question: "Do you rarely have a headache?",
        answers: ["Yes", "No"],
        pointAnswer: 1,
    },
    {
        id: 14,
        type: "singleAnswer",
        question: "Do you sweat a little even in the cold days?",
        answers: ["Yes", "No"],
        pointAnswer: 0,
    },
    {
        id: 15,
        type: "singleAnswer",
        question: "Does your stomach often disturbances you?",
        answers: ["Yes", "No"],
        pointAnswer: 0,
    },
];
