export const QUESTIONS = [
    {
        id: 1,
        type: "singleAnswer",
        question: "Test question 1",
        answers: ["Answer 1", "Answer 2", "Answer 3", "Answer 4"],
        correctAnswer: 2,
    },
    {
        id: 2,
        type: "singleAnswer",
        question: "Test question 2",
        answers: ["Answer 1", "Answer 2", "Answer 3", "Answer 4"],
        correctAnswer: 1,
    },
    {
        id: 3,
        type: "singleAnswer",
        question: "Test question 3",
        answers: ["Answer 1", "Answer 2", "Answer 3", "Answer 4"],
        correctAnswer: 1,
    },
    {
        id: 4,
        type: "singleAnswer",
        question: "Test question 4",
        answers: ["Answer 1", "Answer 2", "Answer 3", "Answer 4"],
        correctAnswer: 0,
    },
    {
        id: 5,
        type: "singleAnswer",
        question: "Test question 5",
        answers: ["Answer 1", "Answer 2", "Answer 3", "Answer 4"],
        correctAnswer: 3,
    },
    {
        id: 6,
        type: "multipleAnswer",
        question: "Test question 6",
        answers: ["Answer 1", "Answer 2", "Answer 3", "Answer 4"],
        correctAnswers: [1, 3],
    },
    {
        id: 7,
        type: "multipleAnswer",
        question: "Test question 7",
        answers: ["Answer 1", "Answer 2", "Answer 3", "Answer 4"],
        correctAnswers: [1, 3],
    },
    {
        id: 8,
        type: "multipleAnswer",
        question: "Test question 8",
        answers: ["Answer 1", "Answer 2", "Answer 3", "Answer 4"],
        correctAnswers: [1, 3],
    },
    {
        id: 9,
        type: "multipleAnswer",
        question: "Test question 9",
        answers: ["Answer 1", "Answer 2", "Answer 3", "Answer 4"],
        correctAnswers: [1, 3],
    },
    {
        id: 10,
        type: "multipleAnswer",
        question: "Test question 10",
        answers: ["Answer 1", "Answer 2", "Answer 3", "Answer 4"],
        correctAnswers: [1, 3],
    },
    {
        id: 11,
        type: "multipleAnswer",
        question: "Test question 11",
        answers: ["Answer 1", "Answer 2", "Answer 3", "Answer 4"],
        correctAnswers: [1, 3],
    },
];