export const QUESTIONS = [
    {
        id: 1,
        type: "singleAnswer",
        question: "What is the capital of France?",
        answers: ["Berlin, Germany", "Madrid, Spain", "Paris, France", "Rome, Italy"],
        correctAnswer: 2,
    },
    {
        id: 2,
        type: "singleAnswer",
        question: "Which planet is known as Red Planet?",
        answers: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: 1,
    },
    {
        id: 3,
        type: "singleAnswer",
        question: "Who wrote 'Hamlet' and 'Macbeth'?",
        answers: ["Mark Twain", "William Shakespeare", "Leo Tolstoy", "Jane Austen"],
        correctAnswer: 1,
    },
    {
        id: 4,
        type: "singleAnswer",
        question: "What is the chemical symbol for water?",
        answers: ["O2", "CO2", "H2O", "NaCl"],
        correctAnswer: 2,
    },
    {
        id: 5,
        type: "singleAnswer",
        question: "Which ocean is the largest on Earth?",
        answers: ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"],
        correctAnswer: 2,
    },
    {
        id: 6,
        type: "multipleAnswer",
        question: "Which animals are mammals?",
        answers: ["Dolphin", "Crocodile", "Elephant", "Eagle"],
        correctAnswers: [0, 2],
    },
    {
        id: 7,
        type: "multipleAnswer",
        question: "Which are programming languages?",
        answers: ["Python", "HTML", "Java", "Photoshop"],
        correctAnswers: [0, 2],
    },
    {
        id: 8,
        type: "multipleAnswer",
        question: "Which countries are in Europe?",
        answers: ["Canada", "France", "Italy", "Japan"],
        correctAnswers: [1, 2],
    },
    {
        id: 9,
        type: "multipleAnswer",
        question: "Select renewable energy sources.",
        answers: ["Wind Power", "Coal Energy", "Solar Power", "Natural Gas"],
        correctAnswers: [0, 2],
    },
    {
        id: 10,
        type: "multipleAnswer",
        question: "Which are types of cloud computing?",
        answers: ["SaaS", "IaaS", "Windows", "PaaS"],
        correctAnswers: [0, 1, 3],
    },
    {
        id: 11,
        type: "multipleAnswer",
        question: "Which planets are gas giants?",
        answers: ["Venus", "Jupiter", "Saturn", "Mercury"],
        correctAnswers: [1, 2],
    },

    {
        id: 12,
        type: "percentAnswer",
        question: "How stupid do you think you are?",
    },
];
